apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-prod
  labels:
    app: flask-app-deployment
spec:
  selector:
    app: flask-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  